# Generated by Django 5.1.3 on 2024-11-28 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Blog')),
                ('content', models.TextField(blank=True, verbose_name='Blog')),
                ('photo', models.ImageField(blank=True, upload_to='blog_photos/%Y/%m/%d/', verbose_name='Blog')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Blog')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Blog')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.blog')),
            ],
            options={
                'db_table': 'MainBlog',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Gallery')),
                ('description', models.TextField(blank=True, verbose_name='Gallery')),
                ('image', models.ImageField(default='default1.jpg', upload_to='GIMG/%Y/%m/%d', verbose_name='Gallery')),
                ('demo_link', models.CharField(blank=True, max_length=200, verbose_name='Gallery')),
                ('source_link', models.CharField(blank=True, max_length=200, verbose_name='Gallery')),
                ('vote_total', models.IntegerField(blank=True, default=0, verbose_name='Gallery')),
                ('vote_ratio', models.IntegerField(blank=True, default=0, verbose_name='Gallery')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Gallery')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.gallery')),
            ],
            options={
                'db_table': 'MainGallery',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Profile')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Profile')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Profile')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Profile')),
                ('is_active', models.BooleanField(default=True, verbose_name='Profile')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Profile')),
                ('phone', models.CharField(blank=True, max_length=14, verbose_name='Profile')),
                ('avatar', models.ImageField(blank=True, upload_to='prof/%Y/%m/%d', verbose_name='Profile')),
                ('friends', models.ManyToManyField(blank=True, related_name='mainfriends', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nameuser', to='main.profile')),
            ],
            options={
                'db_table': 'MainProfile',
            },
        ),
        migrations.CreateModel(
            name='V_Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='V_Gallery')),
                ('description', models.TextField(blank=True, verbose_name='V_Gallery')),
                ('video', models.FileField(default='default.mov', upload_to='GVD/%Y/%m/%d', verbose_name='V_Gallery')),
                ('demo_link', models.CharField(blank=True, max_length=200, verbose_name='V_Gallery')),
                ('source_link', models.CharField(blank=True, max_length=200, verbose_name='V_Gallery')),
                ('vote_total', models.IntegerField(blank=True, default=0, verbose_name='V_Gallery')),
                ('vote_ratio', models.IntegerField(blank=True, default=0, verbose_name='V_Gallery')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='V_Gallery')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.v_gallery')),
            ],
            options={
                'db_table': 'MainVGallery',
            },
        ),
    ]
