# Generated by Django 5.1.3 on 2024-11-29 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_relationshipmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelationshipManager',
        ),
    ]
