# Generated by Django 5.1.3 on 2024-11-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_friendrequest_to_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('first_login', models.DateTimeField(null=True)),
                ('phone', models.CharField(blank=True, max_length=14)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='prof/%Y/%m/%d')),
                ('friends', models.ManyToManyField(blank=True, to='users.user')),
            ],
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
