# Generated by Django 5.1.3 on 2024-11-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_delete_friendrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
